### ISSUE TITLE
Tracking "évènements" 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/monconvertisseurco2#91]
C'est pas vraiment une issue mais je me dis en complément de nos tests utilisateurs et pour voir ce qui fonctionne en terme de navigation, est-ce qu'on pourrait tracker les éléments suivants ?  : 

- [x] Sliders infographies
- [x] Clic lien "Comprendre le CO2e" 
- [x] Bouton Partager 
- [x] Bouton Télécharger (infographie)
- [x] Bouton "Comparer" dans les équivalences 
- [x] Recherche ? (et recherche par catégorie suggérée?) 

Autres si vous voyez autres choses ?

**Comment by florianpanchout** [comment]
Done
